services:
  dev:
    entrypoint:
    - sleep
    - infinity
    image: acathe/dev-environments-default:latest
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
